name: Build react-sample

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: npm
          cache-dependency-path: src/react-sample/package-lock.json
      - name: Init NodeJS env
        run: |
          set -x
          cd src/react-sample
          node -v
          npm install -g next@11.1.1
          npm install
      - name: Build with Next.js
        run: |
          cd src/react-sample
          next build
